### PR TITLE
Added block for public transport.

### PR DESCRIPTION
**Pull request by ultrara1n**
Created a block for public transport.
Currently the whole area of VVS is supported with live data from https://efa-api.asw.io.
This is in fact Stuttgart, Germany and a big part around this place.
To call the function properly, you will need the correct station id from: https://efa-api.asw.io/api/v1/station/

So for Stuttgart Central Station the data will come from https://efa-api.asw.io/api/v1/station/5006118/departures/

Then the data will be collected and shown with possible delays.
If created it mostly customizable so a typical call from config.js looks like this:
var publictransport = {}
publictransport.hbf= { station: '5006118', provider: 'VVS', icon: 'train', interval: 15, results: 5 };

icon is simply font-awesome without fa, interval = time in seconds for refreshing the data, and results = number of shown results. Also possible is to customize the width, but i would not change the value of 12 because of the size of the output.

### CODE REVIEW

**Comment by robgeerts** [comment]
Like it! :)
You really did a great job and will merge this in beta.
Will add a separate topic for this module and add more schedules for other transport companies....

**Comment by ultrara1n** [comment]
I'm glad the script is working after merging & git pull.
Had the fear that it will crash the whole Dashticz setup because of missing symbol somewhere 😆

**Comment by robgeerts** [comment]
It looks great, although 'Geplant' needs to be translated ;)
Topic can be found here: http://www.domoticz.com/forum/viewtopic.php?f=67&t=17568

**Comment by ultrara1n** [comment]
Missed this, you are right. Pull request sended, could not have gone to bed before fixing this.

**Pull request merged**
