### PR TITLE
Streamplayer improvements

### PR DESCRIPTION
**Pull request by lokonli**
Add class when in playing state to enable styling via custom.css.
Add error handling.

### CODE REVIEW

**Comment by HansieNL** [comment]
Thanks a lot for making this possible, but how to use this in custom.css? (Tried several options, but didn't succeed) I wanna use #F2F2F2 for pause color and #FFFFFF for playing color.

**Comment by lokonli** [comment]
I still have to update the documentation :)
Add the following to custom.css to change the colors:

div[data-id='streamplayer'] > div {
  background-color: blue !important;
}

div[data-id='streamplayer'].playing > div {
  background-color: orange !important;
}

**Comment by HansieNL** [comment]
Works like a charm!

**Comment by HansieNL** [comment]
Because allmost every block has an icon it would be great to have one for this block too.
4OtwTZHmHa
This is a photoshoped image by the way.
I'll send a pr for the image radio-streaming.png

**Pull request merged**
