### PR TITLE
Fixes related to language and thermostat setpoints

### PR DESCRIPTION
**Pull request by paalkr**
- Correctly render non ASCII characters in selector switches
Before fix
image
After fix
image
- Corrected wrong localization code used for Norwegian, from Norwegian Nynorsk (nn_NO) to Norwegian Bokmål (nb_NO), http://www.lingoes.net/en/translator/langcode.htm
Norwegian Nynorsk is a different written language, only used by approx 10% of the Norwegian population. The content in the previous nn_NO.json file was actually in Norwegian Bokmål not Norwegian Nynorsk.
- Minor correction to Norwegian translation
- Make max and min range for setpoints configurable

### CODE REVIEW

**Comment by HansieNL** [comment]
I added a new tab Other to the settings screen where you can set the min/max setpoint.
[settings.js.txt](https://github.com/Dashticz/dashticz_v2/files/2849363/settings.js.txt)
[en_US.json.txt](https://github.com/Dashticz/dashticz_v2/files/2849364/en_US.json.txt)
[main.js.txt](https://github.com/Dashticz/dashticz_v2/files/2849365/main.js.txt)
[nl_NL.json.txt](https://github.com/Dashticz/dashticz_v2/files/2849366/nl_NL.json.txt)

**Comment by paalkr** [comment]
Added on option to hide the block title, so the data value can take up more space.

```
blocks['567_1'] = {} //utetemperatur
blocks['567_1']['title'] = 'Utetemperatur'
blocks['567_1']['width'] = 2;
blocks['567_1']['hide_title'] = true;
blocks['567_1']['last_update'] = true; 
```

```
/* Outdoor temp font size */
.block_567_1 .title { font-size: 23px; !important; }
```

image

**Comment by robgeerts** [comment]
Translation files are updating, could you fix the conflicts?

**Comment by paalkr** [comment]
Sure, I will, but unfortunately I'm not too familiar with how to solve conflicts for pull requests. The lang/nn_NO.json is invalid and should not be part of the source tree. Invalid as it's for "Nynorsk" not "Bokmål", which is the official written language in Norway.

**Comment by lokonli** [comment]
I propose to keep both files: nb_NO.json for bokmal and nn_NO.json for nynorsk.
Someone has to make the translation to nynorsk, but probably bokmal is the most easy to use as starting point.

I've recreated the project on lokalise.co to make the translation files. If you want to contribute to the translations please create an account on lokalise.co and send me the email address you used. I'll then add you to the translation contributors.

**Comment by paalkr** [comment]
OK, keeping both is OK with me. We then need to support both Bokmål (default) and Nynorsk language options in settings and for calendar lang etc.

What do I need to do to solve the conflict, so that the other commits can get merged?
I will sign up for lokalise.co for future contributions to translation.

**Comment by lokonli** [comment]
Git/github also is pretty new for me ...

Can you remove the first commit from this PR?
Only the changes to main.js and settings.js are needed.

Probably otherwise you have to add a new commit to your local branch, with the two languages files from the current beta. I think I've included all your improvement to nb_NO already.

Can you also add the changes to  settings.js and main.js as proposed by Hansie.nl?

Maybe that's even easier: make a new PR bases on settings.js and main.js from Hansie.nl.
Close this PR.

**Comment by paalkr** [comment]
OK, so I reverted the commit. Let's see about these other changes.
I don't think I can create a new PR before this one is closed, by you...?

**Comment by paalkr** [comment]
If you merge and close this PR, I will proceed adding the other changes in a new PR. I think that is the easiest with my limited git skills.

**Comment by paalkr** [comment]
Thx

**Comment by paalkr** [comment]
I have now as you suggested opened a new PR to add the missing parts into the settings.js.
https://github.com/Dashticz/dashticz_v2/pull/442

**Pull request merged**
