### PR TITLE
Add the possibility to show several weather forecast days.

### PR DESCRIPTION
**Pull request by lokonli**
See https://www.domoticz.com/forum/viewtopic.php?f=67&t=24073&start=40#p203854

### CODE REVIEW

**Comment by HansieNL** [comment]
I did add the  following to settings.js:
settingList['weather']['owm_days'] = {};
settingList['weather']['owm_days']['title'] = language.settings.weather.owm_days;
settingList['weather']['owm_days']['type'] = 'text';
settingList['weather']['owm_days']['help'] = language.settings.weather.owm_days_help;

settingList['weather']['owm_cnt']['help'] = language.settings.weather.owm_cnt_help;

I did add the  following to nl_NL.json:
"owm_days": "Voorspelling in dagen of standaard (1 = dagen, 0 = standaard)",
"owm_days_help": "Voer 1 in voor weergave voorspelling in dagen, 0 voor de Open Weather Map standaard 3 uurs voorspelling",
"owm_cnt_help": "Aantal weer te geven kolommen. Bij dagen weergave is 5 het maximaal aantal",

And I did  add the  following to en_US.json:
"owm_days": "Forecast in days or default (1 = days, 0 = default)",
"owm_days_help": "Enter 1 for showing forecast in days, 0 for the Open Weather Map default 3 hour forecast",
"owm_cnt_help": "Number of columns to show. If showing days, max is 5",

**Comment by lokonli** [comment]
I've added the changes to the PR.

**Comment by HansieNL** [comment]
Changed some settings:
Days view and min temperature are a switch now. Also updated weather_owm.js to latest version of toro and added owm_days and owm_min.

[en_US.json.txt](https://github.com/Dashticz/dashticz_v2/files/2774099/en_US.json.txt)
[nl_NL.json.txt](https://github.com/Dashticz/dashticz_v2/files/2774100/nl_NL.json.txt)
[settings.js.txt](https://github.com/Dashticz/dashticz_v2/files/2774101/settings.js.txt)
[weather_owm.js.txt](https://github.com/Dashticz/dashticz_v2/files/2774139/weather_owm.js.txt)

Oops... Sorry you have to edit the language files again.

**Comment by lokonli** [comment]
@HansieNL I'm merging the changes in the PR. Thanks for your contribution. Try to use the latest version of the files on Github. Makes life a bit easier...

**Pull request merged**
