### PR TITLE
Refactored language inclusion

### PR DESCRIPTION
**Pull request by ultrara1n**
In preperation for translation the settings screen, i've made a fundamental change to the whole language inclusion. Since there are several areas it is easier to use the JSON file format and read the files via jquery. Also it is now possible to translate and add strings via https://lokalise.co.
That means you do not have to add a new string to every file, but add it centrally at the localization platform and build the new files afterwards. Much less effort and work.

I think and i hope i've changed all occurences of the old language inclusion, but will look at it through the day, so please **do not merge** at the moment.

### CODE REVIEW

**Comment by robgeerts** [comment]
Amazing, this looks great, also take a look at vender/nzbget/nzbget.js
But after you tell me to merge, I can fix these things too.

**Comment by ultrara1n** [comment]
Okay, i've  made some tests with different languages and there shouldn't be a critical error, so you could merge if you want :)

**Comment by robgeerts** [comment]
Will do!
Thank you!!

**Comment by robgeerts** [comment]
Something went wrong when merging, committing, branch is now called Beta, not beta...
Sorry for the inconvenience!

**Comment by ultrara1n** [comment]
No problem! The translation of the settings screen is almost finished, will push it later this day.

**Comment by robgeerts** [comment]
I've added some settings in Beta... (Garbage)

**Pull request merged**
