### PR TITLE
Solved issue #74 with adding graphes

### PR DESCRIPTION
**Pull request by ultrara1n**
https://github.com/robgeerts/dashticz_v2/issues/74

### CODE REVIEW

**Comment by robgeerts** [comment]
Thanks.
But now there's no difference between if(popup) and the else ?

**Comment by ultrara1n** [comment]
Thats right, the question is, why should there be a difference?
Let's just delete the if & else, another line saved.

**Comment by robgeerts** [comment]
Well, thats because we can show the graph inline and in a popup, there could be a difference the way tha graph reacts...

**Comment by ultrara1n** [comment]
Okay, haven't had that in mind.
There is problem with identifying the display method, when the popup appears, the detection is correct, but if you click a button it thinks that you are using it inline, i will have a look at this.

**Comment by ultrara1n** [comment]
`onclick="showGraph('+idx+',\''+orgtitle+'\',\''+label+'\',\'last\',\''+current+'\',true,\''+sensor+'\');"`

The boolean or another value for popup at the end of showGraph() was missing.

**Comment by robgeerts** [comment]
Thanks!!

**Pull request merged**
